name: CI Rust
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run All Tests
        uses: MarcoPolo/cargo@a527bf4d534717ff4424a84446c5d710f8833139
        with:
          command: test
          args: --workspace
          working-directory: server
