name: CI Rust
on: [push, pull_request]

jobs:
  build:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        env:
          PWD: ${{ env.PWD }}/server
        with:
          command: build
          args: --release
      - name: Run All Tests
        uses: actions-rs/cargo@v1
        env:
          PWD: ${{ env.PWD }}/server
        with:
          command: test
