name: CI Rust
on: [push, pull_request]

jobs:
  build:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: MarcoPolo/cargo@a527bf4d534717ff4424a84446c5d710f8833139
        with:
          command: build
          working-directory: server
      - name: Run All Tests
        uses: MarcoPolo/cargo@a527bf4d534717ff4424a84446c5d710f8833139
        with:
          command: test
          working-directory: server
