name: CI Rust
on: [push, pull_request]

jobs:
  build:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: "cd server && cargo build --release"
      - name: Run All Tests
        run: "cd server && cargo test"
