name: CI Rust
on: [push, pull_request]

jobs:
  build:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd server
      - name: Build
        working-directory: ./server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Run All Tests
        working-directory: ./server
        uses: actions-rs/cargo@v1
        with:
          command: test
