name: Lint Rust
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Lint Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Lint
        uses: MarcoPolo/cargo@a527bf4d534717ff4424a84446c5d710f8833139
        with:
          command: clippy
          args: --workspace -- -D warnings
          working-directory: server
